name = "aris"
main = "_worker.js"
compatibility_date = "2023-05-26"
[[routes]]
pattern = "aripin.terahost.biz.id"
custom_domain = true
pattern = "dev.speedtest.net.terahost.biz.id"
custom_domain = true
pattern = "cdn.who.int.terahost.biz.id"
custom_domain = true
# node_compat = true
workers_dev = true

[vars]
# PROXYIP = "211.230.110.231:50008"
UUID = "80572ef5-cef5-442d-97e5-345fa2399454"
# SOCKS5 = "127.0.0.1:1080"
# SOCKS5_RELAY = "true"
